import type { ConceptSeed } from '../helpers';

export const mathConcepts: ConceptSeed[] = [
  // ── Number ─────────────────────────────────────────────────
  {
    id: 'math.number.integers',
    domain: 'Number',
    skill: 'Operations',
    name: 'Integers & order of operations',
    missionName: 'Rune Calculator',
    description: 'Negative numbers and BIDMAS / PEMDAS.',
    lesson: 'Brackets → Indices → × ÷ (left to right) → + − (left to right).',
  },
  {
    id: 'math.number.fractions',
    domain: 'Number',
    skill: 'Fractions',
    name: 'Fractions',
    missionName: 'Split Crystal',
    description: 'Adding, multiplying and simplifying fractions.',
    lesson: 'To add fractions find a common denominator. To multiply, multiply tops and bottoms.',
  },
  {
    id: 'math.number.percent',
    domain: 'Number',
    skill: 'Percentages',
    name: 'Percentages',
    missionName: 'Merchant\'s Scale',
    description: 'Percent of a quantity, percentage change.',
    prerequisites: ['math.number.fractions'],
    lesson: 'x% of N = N × x ÷ 100. A 20% increase means × 1.2.',
  },
  {
    id: 'math.number.powers',
    domain: 'Number',
    skill: 'Powers',
    name: 'Powers & roots',
    missionName: 'Power Spire',
    description: 'Squares, cubes, square roots and index laws.',
    lesson: 'aᵐ × aⁿ = aᵐ⁺ⁿ. √(n²) = n.',
  },
  // ── Algebra ────────────────────────────────────────────────
  {
    id: 'math.algebra.expressions',
    domain: 'Algebra',
    skill: 'Expressions',
    name: 'Simplifying expressions',
    missionName: 'Alchemist\'s Table',
    description: 'Collecting like terms, expanding brackets, substitution.',
    lesson: 'Only like terms combine: 3x + 2x = 5x, but 3x + 2y stays.',
  },
  {
    id: 'math.algebra.linear',
    domain: 'Algebra',
    skill: 'Equations',
    name: 'Linear equations',
    missionName: 'Balance Bridge',
    description: 'Solving ax + b = c and equations with x on both sides.',
    prerequisites: ['math.algebra.expressions'],
    lesson: 'Do the same thing to both sides. Undo + and − first, then × and ÷.',
  },
  {
    id: 'math.algebra.inequalities',
    domain: 'Algebra',
    skill: 'Inequalities',
    name: 'Linear inequalities',
    missionName: 'Gatekeeper',
    description: 'Solving inequalities; flipping the sign when multiplying by a negative.',
    prerequisites: ['math.algebra.linear'],
    lesson: 'Solve like an equation, but flip < / > when you multiply or divide by a negative number.',
  },
  {
    id: 'math.algebra.systems',
    domain: 'Algebra',
    skill: 'Equations',
    name: 'Simultaneous equations',
    missionName: 'Twin Locks',
    description: 'Two equations, two unknowns.',
    prerequisites: ['math.algebra.linear'],
    lesson: 'Add or subtract the equations to eliminate one letter, then substitute back.',
  },
  {
    id: 'math.algebra.quadratics',
    domain: 'Algebra',
    skill: 'Quadratics',
    name: 'Quadratic equations',
    missionName: 'Parabola Peaks',
    description: 'Factorising and solving x² + bx + c = 0.',
    prerequisites: ['math.algebra.expressions'],
    lesson: 'Find two numbers that multiply to c and add to b. Then (x + p)(x + q) = 0.',
  },
  // ── Geometry ───────────────────────────────────────────────
  {
    id: 'math.geometry.angles',
    domain: 'Geometry',
    skill: 'Angles',
    name: 'Angles',
    missionName: 'Compass Court',
    description: 'Angles in triangles, on lines and in polygons.',
    lesson: 'Triangle: 180°. Straight line: 180°. Around a point: 360°. Polygon interior sum: (n − 2) × 180°.',
  },
  {
    id: 'math.geometry.area',
    domain: 'Geometry',
    skill: 'Measurement',
    name: 'Area & perimeter',
    missionName: 'Land Surveyor',
    description: 'Rectangles, triangles, trapezia.',
    lesson: 'Triangle = ½ × base × height. Trapezium = ½ × (a + b) × h.',
  },
  {
    id: 'math.geometry.pythagoras',
    domain: 'Geometry',
    skill: 'Triangles',
    name: 'Pythagoras\' theorem',
    missionName: 'Ladder of Ages',
    description: 'a² + b² = c² in right-angled triangles.',
    prerequisites: ['math.number.powers'],
    lesson: 'The hypotenuse is the longest side, opposite the right angle: c² = a² + b².',
  },
  {
    id: 'math.geometry.circles',
    domain: 'Geometry',
    skill: 'Measurement',
    name: 'Circles',
    missionName: 'Moon Rings',
    description: 'Circumference and area of circles.',
    lesson: 'C = 2πr, A = πr². Use π ≈ 3.14.',
  },
  // ── Statistics & combinatorics ─────────────────────────────
  {
    id: 'math.stats.average',
    domain: 'Statistics',
    skill: 'Averages',
    name: 'Mean, median, mode',
    missionName: 'Census Hall',
    description: 'Finding and comparing averages.',
    lesson: 'Mean = total ÷ count. Median = middle value after sorting.',
  },
  {
    id: 'math.stats.probability',
    domain: 'Statistics',
    skill: 'Probability',
    name: 'Probability',
    missionName: 'Dice Dungeon',
    description: 'Simple and combined probability.',
    lesson: 'P = favourable outcomes ÷ total outcomes. Independent events: multiply.',
  },
  {
    id: 'math.combinatorics.counting',
    domain: 'Combinatorics',
    skill: 'Counting',
    name: 'Counting principles',
    missionName: 'Many Paths',
    description: 'Multiplication principle, arrangements, handshakes.',
    lesson: 'If one choice has m options and the next has n, together there are m × n.',
  },
  {
    id: 'math.reasoning.word-problems',
    domain: 'Mathematical Reasoning',
    skill: 'Modelling',
    name: 'Word problems',
    missionName: 'Quest Board',
    description: 'Turning stories into equations.',
    prerequisites: ['math.algebra.linear'],
    lesson: 'Name the unknown (let x = …), write the equation, solve, then check the answer makes sense.',
  },
];
