import type { ConceptSeed } from '../helpers';

export const englishConcepts: ConceptSeed[] = [
  // ── Vocabulary ─────────────────────────────────────────────
  {
    id: 'en.vocab.everyday',
    domain: 'Vocabulary',
    skill: 'Core words',
    name: 'Everyday vocabulary',
    missionName: 'Village Market',
    description: 'High-frequency words for daily life, school and family.',
    cefr: 'A2',
    lesson: 'Learn words in groups (food, travel, school). Say each word in a sentence about your own life.',
  },
  {
    id: 'en.vocab.synonyms',
    domain: 'Vocabulary',
    skill: 'Word meaning',
    name: 'Synonyms',
    missionName: 'Mirror Grove',
    description: 'Words with similar meanings — essential for IELTS paraphrasing.',
    cefr: 'B1',
    prerequisites: ['en.vocab.everyday'],
    lesson: 'IELTS questions rarely repeat the text\'s words. "Rapid" in a question may be "fast" in the passage.',
    examRefs: ['IELTS Reading: paraphrase matching'],
  },
  {
    id: 'en.vocab.academic',
    domain: 'Vocabulary',
    skill: 'Academic words',
    name: 'Academic vocabulary',
    missionName: 'Scholar\'s Tower',
    description: 'Academic Word List items used in IELTS Reading and Writing.',
    cefr: 'B2',
    prerequisites: ['en.vocab.synonyms'],
    lesson: 'Academic words like "significant", "evidence", "impact" appear in almost every IELTS passage.',
    examRefs: ['IELTS Writing Task 2: lexical resource'],
  },
  {
    id: 'en.vocab.collocations',
    domain: 'Vocabulary',
    skill: 'Word partners',
    name: 'Collocations',
    missionName: 'Twin Bridges',
    description: 'Words that naturally go together: "make a decision", "heavy rain".',
    cefr: 'B1',
    prerequisites: ['en.vocab.everyday'],
    lesson: 'We "make" a decision but "do" homework. Learn verbs together with their nouns.',
  },
  {
    id: 'en.vocab.word-forms',
    domain: 'Vocabulary',
    skill: 'Word building',
    name: 'Word forms',
    missionName: 'Shapeshifter Forge',
    description: 'Noun / verb / adjective / adverb forms: decide → decision → decisive.',
    cefr: 'B1',
    prerequisites: ['en.vocab.everyday'],
    lesson: 'Suffixes signal the word class: -tion (noun), -ive/-ful (adjective), -ly (adverb), -ise/-ify (verb).',
    examRefs: ['IELTS Listening/Reading: gap-fill word form'],
  },
  // ── Grammar ────────────────────────────────────────────────
  {
    id: 'en.grammar.tenses',
    domain: 'Grammar',
    skill: 'Verb tenses',
    name: 'Past simple vs present perfect',
    missionName: 'Clockwork Keep',
    description: 'Choosing between finished time (yesterday) and unfinished time (ever, since, yet).',
    cefr: 'A2',
    lesson: 'Finished time word (yesterday, in 2020) → past simple. Life experience or "since/for/yet/already" → present perfect.',
  },
  {
    id: 'en.grammar.passive',
    domain: 'Grammar',
    skill: 'Sentence structure',
    name: 'Passive voice',
    missionName: 'Shadow Swap',
    description: 'be + past participle: "The bridge was built in 1990."',
    cefr: 'B1',
    prerequisites: ['en.grammar.tenses'],
    lesson: 'Passive = be (in the right tense) + past participle. Use it when the action matters more than who did it.',
    examRefs: ['IELTS Writing Task 1: describing processes'],
  },
  {
    id: 'en.grammar.relative',
    domain: 'Grammar',
    skill: 'Sentence structure',
    name: 'Relative clauses',
    missionName: 'Chain Links',
    description: 'who / which / that / whose / where to join ideas.',
    cefr: 'B1',
    lesson: 'who = people, which = things, whose = possession, where = places. Commas mean extra (non-defining) information — no "that".',
  },
  {
    id: 'en.grammar.conditionals',
    domain: 'Grammar',
    skill: 'Conditionals',
    name: 'Conditionals',
    missionName: 'What-If Portal',
    description: 'Zero, first, second and third conditionals.',
    cefr: 'B1',
    prerequisites: ['en.grammar.tenses'],
    lesson: '1st: If + present, will. 2nd: If + past, would. 3rd: If + had done, would have done.',
  },
  {
    id: 'en.grammar.modals',
    domain: 'Grammar',
    skill: 'Modal verbs',
    name: 'Modal verbs',
    missionName: 'Rune of Maybe',
    description: 'must / might / should / can\'t for obligation, advice and deduction.',
    cefr: 'B1',
    lesson: 'Deduction: must (sure yes), might/could (maybe), can\'t (sure no). Modals are followed by the base verb.',
  },
  {
    id: 'en.grammar.comparatives',
    domain: 'Grammar',
    skill: 'Adjectives',
    name: 'Comparatives & superlatives',
    missionName: 'Tallest Tower',
    description: 'bigger / more interesting / the most / as … as.',
    cefr: 'A2',
    lesson: 'Short adjectives: -er / -est. Long adjectives: more / the most. Irregular: good–better–best, bad–worse–worst.',
    examRefs: ['IELTS Writing Task 1: comparing data'],
  },
  // ── Listening ──────────────────────────────────────────────
  {
    id: 'en.listening.numbers',
    domain: 'Listening',
    skill: 'Specific information',
    name: 'Numbers, dates & spelling',
    missionName: 'Echo Numbers',
    description: 'Catching numbers, prices, dates and spelled names.',
    cefr: 'A2',
    lesson: 'Listen for stress: thirTEEN vs THIRty. Write numbers as digits while listening.',
    examRefs: ['IELTS Listening Part 1: form completion'],
  },
  {
    id: 'en.listening.details',
    domain: 'Listening',
    skill: 'Specific information',
    name: 'Listening for detail',
    missionName: 'Whisper Tunnels',
    description: 'Picking out the key fact when distractors are mentioned.',
    cefr: 'B1',
    prerequisites: ['en.listening.numbers'],
    lesson: 'Speakers often change their mind: "Tuesday… no, actually Wednesday". The last answer usually counts.',
    examRefs: ['IELTS Listening Parts 1–3: distractors'],
  },
  {
    id: 'en.listening.main-idea',
    domain: 'Listening',
    skill: 'Gist',
    name: 'Listening for main idea',
    missionName: 'Great Echo Hall',
    description: 'Understanding the speaker\'s overall purpose or opinion.',
    cefr: 'B2',
    prerequisites: ['en.listening.details'],
    lesson: 'Ask: why is the speaker talking? To complain, explain, persuade or advise?',
    examRefs: ['IELTS Listening Part 3–4'],
  },
  // ── Reading ────────────────────────────────────────────────
  {
    id: 'en.reading.main-idea',
    domain: 'Reading',
    skill: 'Skimming',
    name: 'Main idea',
    missionName: 'Map Room',
    description: 'Finding what a paragraph is mostly about.',
    cefr: 'B1',
    lesson: 'Read the first and last sentence of a paragraph first. The main idea covers the whole paragraph, not one detail.',
    examRefs: ['IELTS Reading: matching headings'],
  },
  {
    id: 'en.reading.paraphrase',
    domain: 'Reading',
    skill: 'Paraphrase',
    name: 'Paraphrase recognition',
    missionName: 'Cipher Wall',
    description: 'Recognising the same idea written with different words.',
    cefr: 'B2',
    prerequisites: ['en.vocab.synonyms'],
    lesson: 'Match meaning, not words. "Numbers fell sharply" = "there was a significant decline".',
    examRefs: ['IELTS Reading: sentence completion'],
  },
  {
    id: 'en.reading.inference',
    domain: 'Reading',
    skill: 'Inference',
    name: 'Inference',
    missionName: 'Detective\'s Lantern',
    description: 'Working out what the writer suggests but does not say directly.',
    cefr: 'B2',
    prerequisites: ['en.reading.main-idea'],
    lesson: 'An inference must be supported by clues in the text — not by your own opinion.',
    examRefs: ['IELTS Reading: writer\'s views'],
  },
  {
    id: 'en.reading.tfng',
    domain: 'Reading',
    skill: 'Exam skills',
    name: 'True / False / Not Given',
    missionName: 'Oracle\'s Scales',
    description: 'Deciding whether the text agrees, contradicts, or says nothing.',
    cefr: 'B2',
    prerequisites: ['en.reading.paraphrase'],
    lesson: 'FALSE = the text says the opposite. NOT GIVEN = the text does not say. Never use outside knowledge.',
    examRefs: ['IELTS Reading: T/F/NG'],
  },
];
